[package]
edition = "2021"
name = "upload-pokemon-data"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
serde = {version = "1.0.136", features = ["derive"]}
